networks:
  network:
    name: ${PROJECT_NAME}-network

volumes:
  db-data:
    name: ${PROJECT_NAME}-db-data

services:
  nginx:
    extends:
      file: docker-compose.yml
      service: nginx

  db:
    extends:
      file: docker-compose.yml
      service: db

  asgi:
    extends:
      file: docker-compose.yml
      service: asgi
    volumes:
      - ../src/:/apps/
